using Fleck;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ddj2server
{
    class Program
    {
        static void Main(string[] args)
        {

            FleckLog.Level = LogLevel.Debug;
            var allSockets = new List<IWebSocketConnection>();
            var server = new WebSocketServer("ws://0.0.0.0:8181");
            server.Start(socket =>
            {
                socket.OnOpen = () =>
                {
                    Console.WriteLine("Open!");
                    allSockets.Add(socket);
                };
                socket.OnClose = () =>
                {
                    Console.WriteLine("Close!");
                    allSockets.Remove(socket);
                };
                socket.OnMessage = message =>
                {
                    Console.WriteLine(message);
                    //allSockets.ToList().ForEach(s => s.Send("Echo: " + message));
                    string[] param = message.Split(',');

                    switch (param[0])
                    {
                        case "IMPredictFrMainCal":
                            socket.Send("IMPredictFrMainCal,reply,begin");
                            dll.IMPredictFrMainCal(
                                int.Parse(param[1]),
                                int.Parse(param[2]),
                                int.Parse(param[3]),
                                double.Parse(param[4]),
                                double.Parse(param[5]),
                                int.Parse(param[6]),
                                "", (s) => socket.Send(s));
                            socket.Send("IMPredictFrMainCal,reply,end");
                            break;
                        case "IMEmSzTransCalMain":
                            socket.Send("IMEmSzTransCalMain,reply,begin");
                            dll.IMEmSzTransCalMain("",
                                int.Parse(param[1]),
                                int.Parse(param[2]),
                                int.Parse(param[3]),
                                double.Parse(param[4]),
                                double.Parse(param[5]),
                                double.Parse(param[6]),
                                double.Parse(param[7]),
                                double.Parse(param[8]),
                                int.Parse(param[9]),
                                int.Parse(param[10]),
                                double.Parse(param[11]),
                                double.Parse(param[12]),
                                int.Parse(param[13]),
                                int.Parse(param[14]),
                                double.Parse(param[15]),
                                double.Parse(param[16]),
                                double.Parse(param[17]),
                                double.Parse(param[18]),
                                double.Parse(param[19]),
                                double.Parse(param[20]),
                                double.Parse(param[21]),
                                int.Parse(param[22]),
                                int.Parse(param[23]),
                                int.Parse(param[24]),
                                int.Parse(param[25]),
                                int.Parse(param[26]),
                                double.Parse(param[27]),
                                double.Parse(param[28]),
                                int.Parse(param[29]),
                                int.Parse(param[30]),
                                double.Parse(param[31]),
                                double.Parse(param[32]),
                                double.Parse(param[33]),
                                double.Parse(param[34]),
                                double.Parse(param[35]),
                                double.Parse(param[36]),
                                double.Parse(param[37]),
                                int.Parse(param[38]),
                                int.Parse(param[39]),
                                int.Parse(param[40]),
                                int.Parse(param[41]),
                                dll.str2DoubleArr(param[42], (int.Parse(param[9]) * int.Parse(param[24])) / 2, 4),
                                double.Parse(param[43]),
                                double.Parse(param[44]),
                                double.Parse(param[45]),
                                int.Parse(param[46]),
                                int.Parse(param[47]),
                                double.Parse(param[48]),
                                double.Parse(param[49]),
                                double.Parse(param[50]),
                                int.Parse(param[51]),
                                int.Parse(param[52]),
                                double.Parse(param[53]),
                                double.Parse(param[54]),
                                double.Parse(param[55]),
                                double.Parse(param[56]),
                                double.Parse(param[57]),
                                double.Parse(param[58]),
                                double.Parse(param[59]),
                                double.Parse(param[60]),
                                double.Parse(param[61]),
                                int.Parse(param[62]),
                                int.Parse(param[63]),
                                int.Parse(param[64]),
                                int.Parse(param[65]),
                                int.Parse(param[66]),
                                double.Parse(param[67]),
                                double.Parse(param[68]),
                                int.Parse(param[69]),
                                int.Parse(param[70]),
                                double.Parse(param[71]),
                                double.Parse(param[72]),
                                double.Parse(param[73]),
                                double.Parse(param[74]),
                                double.Parse(param[75]),
                                int.Parse(param[76]),
                                int.Parse(param[77]),
                                int.Parse(param[78]),
                                int.Parse(param[79]),
                                int.Parse(param[80]),
                                int.Parse(param[81]),
                                dll.str2DoubleArr(param[82], (int.Parse(param[46]) * int.Parse(param[64])) / 2, 4),
                                double.Parse(param[83]),
                                double.Parse(param[84]),
                                double.Parse(param[85]),
                                double.Parse(param[86]),
                                double.Parse(param[87]),
                                double.Parse(param[88]),
                                int.Parse(param[89]),
                                double.Parse(param[90]),
                                double.Parse(param[91]),
                                double.Parse(param[92]),
                                double.Parse(param[93]),
                                int.Parse(param[94]),
                                int.Parse(param[95]),
                                int.Parse(param[96]),
                                int.Parse(param[97]),
                                dll.str2DoubleArr(param[98], int.Parse(param[97])),
                                dll.str2DoubleArr(param[99], int.Parse(param[97])),
                                double.Parse(param[100]),
                                double.Parse(param[101]),
                                double.Parse(param[102]),
                                double.Parse(param[103]),
                                double.Parse(param[104]),
                                int.Parse(param[105]),
                                int.Parse(param[106]),
                                dll.str2DoubleArr(param[107], int.Parse(param[106])),
                                dll.str2DoubleArr(param[108], int.Parse(param[106]), 2),
                                int.Parse(param[109]),
                                int.Parse(param[110]),
                                double.Parse(param[111]),
                                int.Parse(param[112]),
                                double.Parse(param[113]),
                                int.Parse(param[114]),
                                double.Parse(param[115]),
                                double.Parse(param[116]),
                                int.Parse(param[117]),
                                int.Parse(param[118]),
                                int.Parse(param[119]),
                                int.Parse(param[120]),
                                double.Parse(param[121]),
                                int.Parse(param[122]),
                                int.Parse(param[123]),
                                double.Parse(param[124]),
                                double.Parse(param[125]),
                                double.Parse(param[126]),
                                int.Parse(param[127]),
                                int.Parse(param[128]),
                                int.Parse(param[129]),
                                int.Parse(param[130]),
                                int.Parse(param[131]),
                                int.Parse(param[132]) * ,
                                int.Parse(param[133]) * ,
                                int.Parse(param[134]) * ,
                                int.Parse(param[135]) * ,
                                int.Parse(param[136]) * ,
                                double.Parse(param[137]) * ,
                                int.Parse(param[138]) * ,
                                int.Parse(param[139]) * ,
                                double.Parse(param[140]) * ,
                                double.Parse(param[141]) * ,
                                int.Parse(param[142]),
                                int.Parse(param[143]) * ,
                                int.Parse(param[144]) * ,
                                int.Parse(param[145]) * ,
                                int.Parse(param[146]),
                                int.Parse(param[147]),
                                int.Parse(param[148]) * ,
                                int.Parse(param[149]) * ,
                                double.Parse(param[150]),
                                double.Parse(param[151]),
                                int.Parse(param[152]),
                                int.Parse(param[153]),
                                int.Parse(param[154]),
                                int.Parse(param[155]),
                                int.Parse(param[156]),
                                int.Parse(param[157]) * ,
                                int.Parse(param[158]) * ,
                                int.Parse(param[159]) * ,
                                int.Parse(param[160]) * ,
                                int.Parse(param[161]) * ,
                                double.Parse(param[162]) * ,
                                int.Parse(param[163]) * ,
                                int.Parse(param[164]) * ,
                                double.Parse(param[165]) * ,
                                double.Parse(param[166]) * ,
                                int.Parse(param[167]),
                                int.Parse(param[168]) * ,
                                int.Parse(param[169]) * ,
                                int.Parse(param[170]) * ,
                                , (s) => socket.Send(s));
                            socket.Send("IMEmSzTransCalMain,reply,end");
                            break;
                        case "IMEmEcSteadCalMain":
                            socket.Send("IMEmEcSteadCalMain,reply,begin");
                            dll.IMEmEcSteadCalMain("", "",
                                int.Parse(param[1]),
                                int.Parse(param[2]),
                                int.Parse(param[3]),
                                double.Parse(param[4]),
                                double.Parse(param[5]),
                                double.Parse(param[6]),
                                int.Parse(param[7]),
                                int.Parse(param[8]),
                                double.Parse(param[9]),
                                double.Parse(param[10]),
                                int.Parse(param[11]),
                                int.Parse(param[12]),
                                double.Parse(param[13]),
                                double.Parse(param[14]),
                                double.Parse(param[15]),
                                double.Parse(param[16]),
                                double.Parse(param[17]),
                                double.Parse(param[18]),
                                double.Parse(param[19]),
                                double.Parse(param[20]),
                                int.Parse(param[21]),
                                int.Parse(param[22]),
                                int.Parse(param[23]),
                                int.Parse(param[24]),
                                int.Parse(param[25]),
                                double.Parse(param[26]),
                                double.Parse(param[27]),
                                int.Parse(param[28]),
                                int.Parse(param[29]),
                                double.Parse(param[30]),
                                double.Parse(param[31]),
                                double.Parse(param[32]),
                                double.Parse(param[33]),
                                double.Parse(param[34]),
                                int.Parse(param[35]),
                                int.Parse(param[36]),
                                int.Parse(param[37]),
                                int.Parse(param[38]),
                                dll.str2DoubleArr(param[39], (int.Parse(param[7]) * int.Parse(param[22])) / 2, 4),
                                double.Parse(param[40]),
                                double.Parse(param[41]),
                                double.Parse(param[42]),
                                int.Parse(param[43]),
                                int.Parse(param[44]),
                                double.Parse(param[45]),
                                double.Parse(param[46]),
                                double.Parse(param[47]),
                                int.Parse(param[48]),
                                int.Parse(param[49]),
                                double.Parse(param[50]),
                                double.Parse(param[51]),
                                double.Parse(param[52]),
                                double.Parse(param[53]),
                                double.Parse(param[54]),
                                double.Parse(param[55]),
                                double.Parse(param[56]),
                                double.Parse(param[57]),
                                double.Parse(param[58]),
                                double.Parse(param[59]),
                                int.Parse(param[60]),
                                int.Parse(param[61]),
                                int.Parse(param[62]),
                                int.Parse(param[63]),
                                int.Parse(param[64]),
                                double.Parse(param[65]),
                                double.Parse(param[66]),
                                int.Parse(param[67]),
                                int.Parse(param[68]),
                                double.Parse(param[69]),
                                double.Parse(param[70]),
                                double.Parse(param[71]),
                                int.Parse(param[72]),
                                int.Parse(param[73]),
                                int.Parse(param[74]),
                                int.Parse(param[75]),
                                dll.str2DoubleArr(param[76], (int.Parse(param[43]) * int.Parse(param[63])) / 2, 4),
                                int.Parse(param[77]),
                                int.Parse(param[78]),
                                double.Parse(param[79]),
                                double.Parse(param[80]),
                                double.Parse(param[81]),
                                double.Parse(param[82]),
                                double.Parse(param[83]),
                                double.Parse(param[84]),
                                double.Parse(param[85]),
                                double.Parse(param[86]),
                                double.Parse(param[87]),
                                int.Parse(param[88]),
                                int.Parse(param[89])
                                , (s) => socket.Send(s));
                            socket.Send("IMEmEcSteadCalMain,reply,end");
                            break;
                        case "IMDbEcStatorCalMain":
                            socket.Send("IMDbEcStatorCalMain,reply,begin");
                            dll.IMDbEcStatorCalMain("",
                                double.Parse(param[1]),
                                double.Parse(param[2]),
                                int.Parse(param[3]),
                                int.Parse(param[4]),
                                double.Parse(param[5]),
                                double.Parse(param[6]),
                                double.Parse(param[7]),
                                double.Parse(param[8]),
                                int.Parse(param[9]),
                                int.Parse(param[10]),
                                double.Parse(param[11]),
                                int.Parse(param[12]),
                                double.Parse(param[13]),
                                double.Parse(param[14]),
                                double.Parse(param[15]),
                                double.Parse(param[16]),
                                double.Parse(param[17]),
                                double.Parse(param[18]),
                                double.Parse(param[19]),
                                double.Parse(param[20]),
                                int.Parse(param[21]),
                                int.Parse(param[22]),
                                double.Parse(param[23]),
                                double.Parse(param[24]),
                                int.Parse(param[25]),
                                double.Parse(param[26]),
                                double.Parse(param[27]),
                                double.Parse(param[28]),
                                double.Parse(param[29]),
                                double.Parse(param[30]),
                                double.Parse(param[31]),
                                double.Parse(param[32]),
                                double.Parse(param[33]),
                                double.Parse(param[34]),
                                double.Parse(param[35]),
                                double.Parse(param[36]),
                                double.Parse(param[37]),
                                double.Parse(param[38]),
                                double.Parse(param[39]),
                                double.Parse(param[40]),
                                int.Parse(param[41]),
                                int.Parse(param[42]),
                                int.Parse(param[43]),
                                int.Parse(param[44]),
                                int.Parse(param[45]),
                                double.Parse(param[46]),
                                (s) => socket.Send(s));
                            socket.Send("IMDbEcStatorCalMain,reply,end");
                            break;
                        case "IMMeEcStatorCalMain":
                            socket.Send("IMMeEcStatorCalMain,reply,begin");
                            dll.IMMeEcStatorCalMain("",
                                int.Parse(param[1]),
                                double.Parse(param[2]),
                                double.Parse(param[3]),
                                double.Parse(param[4]),
                                int.Parse(param[5]),
                                int.Parse(param[6]),
                                double.Parse(param[7]),
                                double.Parse(param[8]),
                                int.Parse(param[9]),
                                double.Parse(param[10]),
                                double.Parse(param[11]),
                                double.Parse(param[12]),
                                double.Parse(param[13]),
                                double.Parse(param[14]),
                                double.Parse(param[15]),
                                int.Parse(param[16]),
                                int.Parse(param[17]),
                                int.Parse(param[18]),
                                int.Parse(param[19]),
                                double.Parse(param[20]),
                                double.Parse(param[21]),
                                double.Parse(param[22]),
                                double.Parse(param[23]),
                                int.Parse(param[24]),
                                int.Parse(param[25]),
                                double.Parse(param[26]),
                                double.Parse(param[27]),
                                int.Parse(param[28]),
                                (s) => socket.Send(s));
                            socket.Send("IMMeEcStatorCalMain,reply,end");
                            break;
                        default:
                            socket.Send("err params");
                            break;
                    }
                };
            });


            var input = Console.ReadLine();
            while (input != "exit")
            {
                foreach (var socket in allSockets.ToList())
                {
                    socket.Send(input);
                }
                input = Console.ReadLine();
            }
        }
    }
}
